#ifndef MTP_DEFS_H
#define MTP_DEFS_H


/*
 * PUBLIC DEFINITIONS
 */

#define MTP_OBJ_UNDEF				0x3000

#define MTP_DATA_UNDEF				0x0000
#define MTP_DATA_INT8				0x0001
#define MTP_DATA_UINT8				0x0002
#define MTP_DATA_INT16				0x0003
#define MTP_DATA_UINT16				0x0004
#define MTP_DATA_INT32				0x0005
#define MTP_DATA_UINT32				0x0006
#define MTP_DATA_INT64				0x0007
#define MTP_DATA_UINT64				0x0008
#define MTP_DATA_INT128				0x0009
#define MTP_DATA_UINT128			0x000A
#define MTP_DATA_ARRAY				0x4000 // Can be used as a modifier on other types
#define MTP_DATA_STRING				0xFFFF


#define MTP_RESP_UNDEF						0x2000
#define MTP_RESP_OK							0x2001
#define MTP_RESP_GENERAL_ERROR				0x2002
#define MTP_RESP_SESSON_NOT_OPEN			0x2003
#define MTP_RESP_INVALID_TRANSACTION_ID		0x2004
#define MTP_RESP_OPERATION_NOT_SUPPORTED	0x2005
#define MTP_RESP_PARAMETER_NOT_SUPPORTED	0x2006
#define MTP_RESP_INCOMPLETE_TRANSFER		0x2007
#define MTP_RESP_INVALID_STORAGE_ID			0x2008
#define MTP_RESP_INVALID_OBJ_HANDLE			0x2009
#define MTP_RESP_PROPERTY_NOT_SUPPORTED		0x200A
#define MTP_RESP_INVALID_OBJECT_FORMAT		0x200B
#define MTP_RESP_STORE_FULL					0x200C
#define MTP_RESP_OBJ_WRITE_PROTECTED		0x200D
#define MTP_RESP_STORE_READ_ONLY			0x200E
#define MTP_RESP_ACCESS_DENIED				0x200F
#define MTP_RESP_NO_THUMBNAIL				0x2010
#define MTP_RESP_SELFTEST_FAIL				0x2011
#define MTP_RESP_PARTIAL_DELETION			0x2012
#define MTP_RESP_STORE_NOT_AVAILABLE		0x2013
#define MTP_RESP_SPECIFICATION_FORMAT_NOT_SUPPORTED	0x2014
#define MTP_RESP_NO_VALID_OBJ_INFO			0x2015
#define MTP_RESP_INVALID_CODE_FORMAT		0x2016
#define MTP_RESP_UNKNOWN_VENDOR_CODE		0x2017
#define MTP_RESP_CAPTURE_ALREADY_TERMINATED	0x2018
#define MTP_RESP_DEVICE_BUSY				0x2019
#define MTP_RESP_INVALID_PARENT_OBJ			0x201A
#define MTP_RESP_INVALID_DEVICE_PROP_FORMAT	0x201B
#define MTP_RESP_INVALID_DEVICE_PROP_VALUE	0x201C
#define MTP_RESP_INVALID_PARAMETER			0x201D
#define MTP_RESP_SESSION_ALREADY_OPEN		0x201E
#define MTP_RESP_TRANSACTION_CANCELLED		0x201F
#define MTP_RESP_SPECIFICATION_DEST_NOT_SUPPORTED	0x2020
#define MTP_RESP_INVALID_OBJ_PROP_CODE		0xA801
#define MTP_RESP_INVALID_OBJ_PROP_FORMAT	0xA802
#define MTP_RESP_INVALID_OBJ_PROP_VALUE		0xA803
#define MTP_RESP_INVALID_OBJ_REFERENCE		0xA804
#define MTP_RESP_GROUP_NOT_SUPPORTED		0xA805
#define MTP_RESP_INVALID_DATASET			0xA806
#define MTP_RESP_SPECIFICATION_GROUP_NOT_SUPPORTED 	0xA807
#define MTP_RESP_SPECIFICATION_DEPTH_NOT_SUPPORTED 	0xA808
#define MTP_RESP_OBJ_TOO_LARGE				0xA809
#define MTP_RESP_OBJ_PROP_NOT_SUPPORTED		0xA80A


#define MTP_OPERATION_SIZE					30
#define MTP_CMD_SIZE						8

/*
 * PUBLIC TYPES
 */

// Used for both operations and responses.
typedef struct __attribute((packed)) {
	uint16_t code;
	uint32_t sessionId;
	uint32_t transactionId;
	uint32_t data[5];
} MTP_Operation_t;

/*
 * PUBLIC FUNCTIONS
 */

/*
 * EXTERN DECLARATIONS
 */

#endif //MTP_DEFS_H
